// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shhhdkkygcmrkdcjroes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaGhka2t5Z2NtcmtkY2pyb2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDg5MzksImV4cCI6MjA1ODkyNDkzOX0.Sb1gkvrfj9LUppmgGTvWL3hYpMm_mDIl4KY3YSIzOIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);